### ISSUE TITLE
Trying to add a geofence crashes app.

### ISSUE THREAD

**Issue by abdul-qudus** [ashwin-phadke/Smart-Home-Security-App#2]
Expected behavior
When app is been open, any operation been performed on the app should not malfunction or create a crash to the app.

Actual behavior
Trying to create a new geofence crashes app instantly.

How to reproduce

Download the app. 

Open app, then register or sign up or create an account using email. 

After, then you click on MANAGE GEOFENCE. From the options displayed.

Then on the fresh page click on the plus option st the lower corner of the page. 

From the pop up, fill all necessary information to add a new geofence. Then click on ADD. 

Bug is visible.

Device: Tecno wx3pro
App version: 1.0 
Operating system: Android Nougat 7.0

Recording of the bug
https://youtu.be/JP_eknA-uG8

**Comment by ashwin-phadke** [comment]
Hey, thank you for bringing this to our notice.

Here are some useful troubleshooting tips :

- Close any running instances of the app.

- Turn on Location Sharing in your general settings and in the app level permissions as well.

- Open the app and test for 'expected behavior'

Notes :
This issue was persistent with post Kitkat devices due to the introduction of app level permissions , but the above steps will help you resolve the issue. If it does not , feel free to comment and share.
